spring.application.name=SecurityP03_Role
spring.security.user.name=root
sprint.security.user.password=root

#this our own web securiy user name and password is not necessary here
#if this is not written then also project runs otherwise if
#it is already written then no worry it will Be override
# through our own userdetailservice implementation
