spring.application.name=Weather-App
weather.api.key=1450d3f7931044e3a7e104230261304
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json
